# Configuration for Ring Universus
# Defined in TOML as per https://toml.io/en/v1.0.0

[initializers]
START_PAUSED = true

[town_initializers]
EXPLORER_FEE_RATIO = 1000       # 10.00%
SYSTEM_EXPLORE_FEE_RATIO = 1000 # 10.00%
EXPLORER_SLOT = 10
MIN_EXPLORE_TIME = 1800         # 0.5 * 3600, 30 mins
MAX_EXPLORE_TIME = 604800       # 7 * 24 * 3600, 7 days
MAX_EXPLORE_REWARDS = 4000      # max 4000 token rewards

[ring_initializers]
DISTANCE = 200000              # 2000 means 20.00
TOWN_MINTING_RATIO = 1000      # 10.00%
TOWN_OVER_MINTING_RATIO = 1000 # 10.00%
TOWN_RATIO_BONUS = 100         # 1.00x
OBLIVION_MINTING_RATIO = 1000  # 10.00%
OBLIVION_RATIO_BONUS = 100     # 1.00x

[coin_initializers]
NAME = "Universus Coin"
SYMBOL = "UNiC"
DECIMALS = 18
TOTAL_SUPPLY = 1_000_000_000

[equipment_initializers]
NAME = "Universus Equipment"
SYMBOL = "UNiE"

[oblivion_initializers]
VALID_DELAY = 259200 # 3 days

[player_initializers]
BASE_MOVE_SPEED = 100                                      # 1.00/s
BASE_ATTACK_POWER = 100                                    # 1.00/s
MIN_TRIP_TIME = 1                                          # 10 * 30, 300 secs
TOWN_MINT_FEE = 200                                        # 100 UNiC
MAX_MINT_TOW_PER_MOVE = 3
TOWN_MINT_RATIO_PER_MOVE = 30                              # 0.3 30%
OBLIVION_MINT_RATIO_PER_MOVE = 30                          # 0.3 30%
SEGMENTATION_DISTANCE_PER_MOVE = 200                       # split moving line with given distance
FEE_ADDRESS = "0xfeEFEEfeefEeFeefEEFEEfEeFeefEEFeeFEEFEeF"
VRF_ADDRESS = "0x3097403B64fe672467345bf159F4C9C5464bD89e"
